// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace GamePlannerWeb.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EventModel
    {
        /// <summary>
        /// Initializes a new instance of the EventModel class.
        /// </summary>
        public EventModel() { }

        /// <summary>
        /// Initializes a new instance of the EventModel class.
        /// </summary>
        public EventModel(int? id = default(int?), string title = default(string), DateTime? date = default(DateTime?), IList<Game> gameOptions = default(IList<Game>), IList<EventRegistration> players = default(IList<EventRegistration>), string workLog = default(string))
        {
            ID = id;
            Title = title;
            Date = date;
            GameOptions = gameOptions;
            Players = players;
            WorkLog = workLog;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GameOptions")]
        public IList<Game> GameOptions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Players")]
        public IList<EventRegistration> Players { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkLog")]
        public string WorkLog { get; set; }

    }
}
