// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace GamePlannerWeb.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GameAssignment
    {
        /// <summary>
        /// Initializes a new instance of the GameAssignment class.
        /// </summary>
        public GameAssignment() { }

        /// <summary>
        /// Initializes a new instance of the GameAssignment class.
        /// </summary>
        public GameAssignment(int? id = default(int?), EventModel eventProperty = default(EventModel), Game game = default(Game), IList<EventRegistration> players = default(IList<EventRegistration>))
        {
            ID = id;
            EventProperty = eventProperty;
            Game = game;
            Players = players;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Event")]
        public EventModel EventProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Game")]
        public Game Game { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Players")]
        public IList<EventRegistration> Players { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Game != null)
            {
                this.Game.Validate();
            }
            if (this.Players != null)
            {
                foreach (var element in this.Players)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
