// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace GamePlannerWeb.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Preference
    {
        /// <summary>
        /// Initializes a new instance of the Preference class.
        /// </summary>
        public Preference() { }

        /// <summary>
        /// Initializes a new instance of the Preference class.
        /// </summary>
        public Preference(int? id = default(int?), EventModel eventProperty = default(EventModel), Game game = default(Game), double? weight = default(double?))
        {
            ID = id;
            EventProperty = eventProperty;
            Game = game;
            Weight = weight;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Event")]
        public EventModel EventProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Game")]
        public Game Game { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Weight")]
        public double? Weight { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Game != null)
            {
                this.Game.Validate();
            }
        }
    }
}
